apiVersion: v1
kind: Service
metadata:
  labels:
    service: llama-gpt-api
  name: llama-gpt-api
spec:
  ports:
    - name: api
      port: 8000
      targetPort: 8000
  selector:
    service: llama-gpt-api
status:
  loadBalancer: {}
