apiVersion: v1
kind: Service
metadata:
  labels:
    service: llama-gpt-ui
  name: llama-gpt-ui
spec:
  ports:
    - name: ui
      port: 3000
      targetPort: 3000
  selector:
    service: llama-gpt-ui
  type: ClusterIP
status:
  loadBalancer: {}
